# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Thomas Madhavan"
description: > # this means to ignore newlines until "email:"
	Thoughts and images 
email: thomas@tmadhavan.com

permalink: "/:title"

#blog logo
logo: "/assets/images/tm_logo.png"
# blog cover
cover: "/assets/images/banner.jpg"

name: 'Thomas Madhavan'
author: 'Thomas Madhavan'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.tmadhavan.com/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tmadhavan
    desc: Follow me on Twitter
    share_url: 
    share_title: 
    share_link: 
    
  - icon:	instagram
    url:	https://instagram.com/thomas.madhavan
    desc: Follow me on Instagram
    share_url: 
    share_title: 
    share_link: 
    
  - icon:	flickr
    url:	https://flickr.com/tmadhavan
    desc: Follow me on Flickr
    share_url: 
    share_title: 
    share_link:   

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/tmadhavan
#    desc:	Fork me on Github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
